// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	SyncPid
	Position
	MovePackege
	BroadCast
	Talk
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncPid struct {
	Pid int32 `protobuf:"varint,1,opt,name=Pid,json=pid" json:"Pid,omitempty"`
}

func (m *SyncPid) Reset()                    { *m = SyncPid{} }
func (m *SyncPid) String() string            { return proto.CompactTextString(m) }
func (*SyncPid) ProtoMessage()               {}
func (*SyncPid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Position struct {
	X float32 `protobuf:"fixed32,1,opt,name=X,json=x" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,json=y" json:"Y,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MovePackege struct {
	P          *Position `protobuf:"bytes,1,opt,name=P,json=p" json:"P,omitempty"`
	ActionData int32     `protobuf:"varint,2,opt,name=ActionData,json=actionData" json:"ActionData,omitempty"`
}

func (m *MovePackege) Reset()                    { *m = MovePackege{} }
func (m *MovePackege) String() string            { return proto.CompactTextString(m) }
func (*MovePackege) ProtoMessage()               {}
func (*MovePackege) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MovePackege) GetP() *Position {
	if m != nil {
		return m.P
	}
	return nil
}

type BroadCast struct {
	Pid int32 `protobuf:"varint,1,opt,name=Pid,json=pid" json:"Pid,omitempty"`
	Tp  int32 `protobuf:"varint,2,opt,name=Tp,json=tp" json:"Tp,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*BroadCast_Content
	//	*BroadCast_P
	//	*BroadCast_ActionData
	Data isBroadCast_Data `protobuf_oneof:"Data"`
}

func (m *BroadCast) Reset()                    { *m = BroadCast{} }
func (m *BroadCast) String() string            { return proto.CompactTextString(m) }
func (*BroadCast) ProtoMessage()               {}
func (*BroadCast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isBroadCast_Data interface {
	isBroadCast_Data()
}

type BroadCast_Content struct {
	Content string `protobuf:"bytes,3,opt,name=Content,json=content,oneof"`
}
type BroadCast_P struct {
	P *Position `protobuf:"bytes,4,opt,name=P,json=p,oneof"`
}
type BroadCast_ActionData struct {
	ActionData int32 `protobuf:"varint,5,opt,name=ActionData,json=actionData,oneof"`
}

func (*BroadCast_Content) isBroadCast_Data()    {}
func (*BroadCast_P) isBroadCast_Data()          {}
func (*BroadCast_ActionData) isBroadCast_Data() {}

func (m *BroadCast) GetData() isBroadCast_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BroadCast) GetContent() string {
	if x, ok := m.GetData().(*BroadCast_Content); ok {
		return x.Content
	}
	return ""
}

func (m *BroadCast) GetP() *Position {
	if x, ok := m.GetData().(*BroadCast_P); ok {
		return x.P
	}
	return nil
}

func (m *BroadCast) GetActionData() int32 {
	if x, ok := m.GetData().(*BroadCast_ActionData); ok {
		return x.ActionData
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BroadCast) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BroadCast_OneofMarshaler, _BroadCast_OneofUnmarshaler, _BroadCast_OneofSizer, []interface{}{
		(*BroadCast_Content)(nil),
		(*BroadCast_P)(nil),
		(*BroadCast_ActionData)(nil),
	}
}

func _BroadCast_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BroadCast)
	// Data
	switch x := m.Data.(type) {
	case *BroadCast_Content:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Content)
	case *BroadCast_P:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.P); err != nil {
			return err
		}
	case *BroadCast_ActionData:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ActionData))
	case nil:
	default:
		return fmt.Errorf("BroadCast.Data has unexpected type %T", x)
	}
	return nil
}

func _BroadCast_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BroadCast)
	switch tag {
	case 3: // Data.Content
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &BroadCast_Content{x}
		return true, err
	case 4: // Data.P
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Position)
		err := b.DecodeMessage(msg)
		m.Data = &BroadCast_P{msg}
		return true, err
	case 5: // Data.ActionData
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &BroadCast_ActionData{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _BroadCast_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BroadCast)
	// Data
	switch x := m.Data.(type) {
	case *BroadCast_Content:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Content)))
		n += len(x.Content)
	case *BroadCast_P:
		s := proto.Size(x.P)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *BroadCast_ActionData:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.ActionData))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Talk struct {
	Content string `protobuf:"bytes,1,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *Talk) Reset()                    { *m = Talk{} }
func (m *Talk) String() string            { return proto.CompactTextString(m) }
func (*Talk) ProtoMessage()               {}
func (*Talk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*SyncPid)(nil), "pb.SyncPid")
	proto.RegisterType((*Position)(nil), "pb.Position")
	proto.RegisterType((*MovePackege)(nil), "pb.MovePackege")
	proto.RegisterType((*BroadCast)(nil), "pb.BroadCast")
	proto.RegisterType((*Talk)(nil), "pb.Talk")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xb1, 0x93, 0x34, 0xe4, 0x5a, 0x21, 0x74, 0x53, 0x04, 0x08, 0x45, 0x19, 0x10, 0x53,
	0x06, 0x78, 0x02, 0x52, 0x06, 0x18, 0x90, 0x2c, 0xd3, 0x01, 0x46, 0x27, 0xb1, 0x2a, 0xab, 0x60,
	0x5b, 0x8d, 0x85, 0xe8, 0x63, 0xf0, 0x1a, 0x3c, 0x25, 0xb6, 0x0b, 0x05, 0xd4, 0xc9, 0xfa, 0xff,
	0x3b, 0xff, 0xff, 0xa7, 0x83, 0xe2, 0x75, 0x5c, 0x36, 0x76, 0x6d, 0x9c, 0x41, 0x6a, 0xbb, 0xfa,
	0x14, 0xf2, 0xc7, 0x8d, 0xee, 0x99, 0x1a, 0xf0, 0x18, 0x12, 0xff, 0x94, 0xa4, 0x22, 0x97, 0x19,
	0x4f, 0xac, 0x1a, 0xea, 0x0b, 0x38, 0x64, 0x66, 0x54, 0x4e, 0x19, 0x8d, 0x33, 0x20, 0x4f, 0x71,
	0x46, 0x39, 0x79, 0x0f, 0xea, 0xb9, 0xa4, 0x5b, 0xb5, 0xa9, 0xef, 0x61, 0xfa, 0x60, 0xde, 0x24,
	0x13, 0xfd, 0x4a, 0x2e, 0x25, 0x9e, 0x00, 0x61, 0x71, 0x75, 0x7a, 0x35, 0x6b, 0x6c, 0xd7, 0xfc,
	0x64, 0x70, 0x62, 0xf1, 0x1c, 0xe0, 0xa6, 0x0f, 0xe2, 0x56, 0x38, 0x11, 0x13, 0x32, 0x0e, 0x62,
	0xe7, 0xd4, 0x1f, 0x04, 0x8a, 0x76, 0x6d, 0xc4, 0x30, 0x17, 0xa3, 0xdb, 0x47, 0xc2, 0x23, 0xa0,
	0x0b, 0xfb, 0xfd, 0x8f, 0x3a, 0xeb, 0xbb, 0xf2, 0xb9, 0xd1, 0x4e, 0x6a, 0x57, 0x26, 0xde, 0x2c,
	0xee, 0x0e, 0x78, 0xde, 0x6f, 0x0d, 0x3c, 0x0b, 0x1c, 0xe9, 0x3e, 0x87, 0xdf, 0xf1, 0x24, 0xd5,
	0x3f, 0x92, 0x2c, 0x24, 0xfa, 0xc1, 0x1f, 0x96, 0x76, 0x02, 0x69, 0x64, 0xaa, 0x20, 0x5d, 0x88,
	0x97, 0x15, 0x96, 0xbf, 0x5d, 0x81, 0xa8, 0xd8, 0x35, 0xb5, 0xd9, 0x27, 0xa5, 0xac, 0xeb, 0x26,
	0xf1, 0xae, 0xd7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x4d, 0x58, 0xf7, 0x64, 0x01, 0x00,
	0x00,
}
